[changelog]
# changelog header
header = "# Changelog\n\n"
#
#All notable changes to this project will be documented in this file.
#
#The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
#and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
#
#"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    ## [Unreleased](https://github.com/vhdirk/dash7-rs/compare/{{ version }}...HEAD)

    ## [{{ version | trim_start_matches(pat="v") }}] {{ timestamp | date(format="%Y-%m-%d") }}

    [{{ version | trim_start_matches(pat="v") }}]: https://github.com/vhdirk/dash7-rs/compare/{{ previous.version }}...{{ version }}
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
# commit_preprocessors = [
#     { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"}, # replace issue numbers
# ]

commit_parsers = [
    { message = "^feat", group = "✨ Features" },
    { message = "^fix", group = "🤕 Fixes" },
    { message = "^doc", group = "📖 Documentation" },
    { message = "release", skip = true },
    { message = ".*", group = "🛠️  Maintenance" },
]
protect_breaking_commits = false
filter_commits = false
# tag_pattern = "v[0-9].*"

ignore_tags = ""
topo_order = false
sort_commits = "oldest"
# limit_commits = 100
