[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
# changelog_config = "config/git-cliff.toml" # use a custom git-cliff configuration
# changelog_update = true # disable changelog updates
dependencies_update = true # update dependencies with `cargo update`
git_release_enable = true # disable GitHub/Gitea releases
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_timeout = "10m" # set a timeout for `cargo publish`
# release_commits = "^feat:" # prepare release only if at least one commit matches a regex
publish = true
release = true
release_always = true
publish_allow_dirty = true # add `--allow-dirty` to `cargo publish`
publish_no_verify = true


[[package]]
name = "dash7"
changelog_path = "dash7/CHANGELOG.md"

[[package]]
name = "dash7-cli"
changelog_path = "dash7-cli/CHANGELOG.md"
changelog_include = ["dash7"]

[changelog]
protect_breaking_commits = true
header = "# Changelog"
body = "Body"
trim = true
sort_commits = "newest"