[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
# changelog_config = "config/git-cliff.toml" # use a custom git-cliff configuration
# changelog_update = true # disable changelog updates
dependencies_update = true # update dependencies with `cargo update`
git_release_enable = true # disable GitHub/Gitea releases
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_allow_dirty = true # add `--allow-dirty` to `cargo publish`
publish_timeout = "10m" # set a timeout for `cargo publish`
release_commits = "^feat:" # prepare release only if at least one commit matches a regex


[[package]]
name = "dash7"

[[package]]
name = "dash7-cli"
changelog_include = ["dash7"]

[changelog]
protect_breaking_commits = true