// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VarInt>>
@sealed
class VarInt extends RustOpaque {
  VarInt.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  VarInt.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        dash7.instance.api.rust_arc_increment_strong_count_VarInt,
    rustArcDecrementStrongCount:
        dash7.instance.api.rust_arc_decrement_strong_count_VarInt,
    rustArcDecrementStrongCountPtr:
        dash7.instance.api.rust_arc_decrement_strong_count_VarIntPtr,
  );

  static VarInt decompress(
          {required int exponent, required int mantissa, dynamic hint}) =>
      dash7.instance.api.crateApiVarintVarIntDecompress(
          exponent: exponent, mantissa: mantissa, hint: hint);

  factory VarInt({required int value, required bool ceil, dynamic hint}) =>
      dash7.instance.api
          .crateApiVarintVarIntNew(value: value, ceil: ceil, hint: hint);

  int get value => dash7.instance.api.crateApiVarintVarIntValue(
        that: this,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VarIntError>>
@sealed
class VarIntError extends RustOpaque {
  VarIntError.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  VarIntError.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        dash7.instance.api.rust_arc_increment_strong_count_VarIntError,
    rustArcDecrementStrongCount:
        dash7.instance.api.rust_arc_decrement_strong_count_VarIntError,
    rustArcDecrementStrongCountPtr:
        dash7.instance.api.rust_arc_decrement_strong_count_VarIntErrorPtr,
  );
}
